version: '3.9'

services:
  nn:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ..:/nn
      - ~/.ssh:/tmp/.ssh:ro
    working_dir: /nn
